### ISSUE TITLE
color is wrong

### ISSUE THREAD

**Issue by icode** [x64Bits/solid-icons#44] opened 2023-06-21 09:16 UTC
![image](https://github.com/x64Bits/solid-icons/assets/972959/a4e0df22-b1e9-4994-895f-2fd3e8eae0a1)

old version is right, latest is wrong, should set default color = curentColor

**Comment by Schlumie** [comment] 2023-06-23 11:14
Some Icons are now black instead of white...

**Comment by densumesh** [comment] 2023-06-30 19:54
yup, worked for me. Had to set the fill: currentcolor prop on each solid-icon.

**Comment by emdede** [comment] 2023-07-08 15:32
Without workaround of adding fill property
![image](https://github.com/x64Bits/solid-icons/assets/64293438/568fedff-8003-4aec-92e2-54fae41b1f41)

With workaround applied
![image](https://github.com/x64Bits/solid-icons/assets/64293438/4406aadd-310c-454f-ba4a-fb49465e7c36)


I have a custom Icon component which takes IconType value and renders a `Dynamic` component which is an imported icon. Colors could be set by either passing the `color` prop or just by inheriting from `currentColor` set by a TW color class. Now both don't work anymore. This is extremely annoying as it forces me to micro-manage colors on a per-icon basis.

My code (shortened):
```
type IconProps = {
  type: IconTypes
  size?: IconSize
  color?: IconColor
  class?: string
}

export const IconType = {
  home: ImHome,
  dashboard: BiSolidDashboard,
  domain: FiGlobe,
} as const

export type IconType = ValuesOf<typeof IconType>

export const IconColor = {
  white: '#ffffff',
  black: '#000000',
} as const

export type IconColor = ValuesOf<typeof IconColor>

export const IconSize = {
  sm: 16,
  md: 20, // default
  lg: 24,
} as const

export type IconSize = ValuesOf<typeof IconSize>

export const Icon: Component<IconProps> = (props) => {
  return (
    <Dynamic
      component={props.type}
      size={props.size ?? IconSize.md}
      color={props.color}
      class={props.class}
    />
  )
}
```

With newest changes I'd have to add a style property of `fill` which maps either color prop or currentColor and also add conditionals on a per-icon basis depending on if they show as intended or not (after visual confirmation). Any update on this in sight? I wanted to sit it out first, thinking it's a bug. But seeing that that it's been like this for a few weeks already, I'd like to ask on current/future status.

**Comment by x64Bits** [comment] 2023-07-08 19:47
Hello, I've been looking at this lately but I couldn't reproduce it, can you send a repro of this on github or codesandbox please?

**Comment by emdede** [comment] 2023-07-09 03:53
@x64Bits 
It seems to be a specific issue with certain icon sets.
https://stackblitz.com/edit/solid-ssr-vite-tj6b2f?file=src%2Froutes%2Findex.tsx

In my application I am using a wide variety of different source sets and the problem seems to be pretty wide-spread.

**Comment by Wantod** [comment] 2023-09-01 16:34
I personally have the problem with versions > 1.0.4.
which is why I think there are so many downloads of this version.
https://www.npmjs.com/package/solid-icons?activeTab=versions

**Comment by emdede** [comment] 2023-09-01 16:51
@Wantod 
Yes, we also rolled back to 1.0.4

**Comment by x64Bits** [comment] 2023-09-08 22:48
Hello everyone, one PR #51 was merge that address this issue, can anyone take a look it's the 1.0.12 versions display the icons correctly?

**Comment by emdede** [comment] 2023-09-09 11:04
@x64Bits 
I've updated[ the example stackblitz ](https://stackblitz.com/edit/solid-ssr-vite-tj6b2f?file=src%2Froutes%2Findex.tsx)from above with the new version and it does indeed seem to be working fine again.

**Comment by x64Bits** [comment] 2023-11-01 17:21
Hi!, thank you very much for all the help, since version 1.1.0 even more problems with the color of the icons have been solved, I will close this issue, greetings!

**Closed by x64Bits** 2023-11-01 17:21 UTC
